### ISSUE TITLE
Harmonize Observation weights and ExtendedSource bg_rms 

### ISSUE THREAD

**Issue by EiffL** [pmelchior/scarlet#129]
As explained in #128 this user got confused by the differences between `bg_rms` and `weights`, seems like the extended source bg_rms could be deduced from the Observation, would make sense to define the noise  level there.

**Comment by fred3m** [comment]
These are slightly different quantities. `weights` is an element-wise weight for each pixel, used in the likelihood calculation. `bg_rms` sets the noise level in each band and is used by extended sources to set a detection threshold. While we could estimate the background RMS using the observation info in the observation I think that it's better to give the user the freedom to specify the background noise level for a few different reasons:

1) The observation only contains image data from the blended region, not the entire image. In HSC/LSST footprints, for example, this only contains the region with flux _above the noise_ (slightly grown to include some noise), so using the footprint to estimate the background RMS will result in a `bg_rms` that is too high. When running on HSC data this often caused source initialization to fail because the code thinks that the background is too high and there aren't enough/any pixels in a source above this artificially high threshold. The `bg_rms` should really be determined from the entire image, not just the blended region, so the user would need to calculate this on outside of scarlet where they have access to an entire exposure.

2) In an image with saturated sources or other artifacts with bad pixels, the `weights` will be set to zero for all of the masked pixels. In this case the `bg_rms` estimate will be low if there are a large number of zero weights. This is not as catastrophic as case 1, only causing sources to grow much larger than they need too, but the gradient descent seems to be better at growing sources than shrinking them so it would still be a nuisance.

So my recommendation would be to try and be more clear in the documentation about the difference between `observation` `weights` and `ExtendedSource` `bg_rms` but I think that users should be given the option of specifying the background level in a blend.

**Comment by pmelchior** [comment]
I mostly disagree with these concerns. In absence of masking there should be no reason why one couldn't use the mean of the (non-zero) weights to set `bg_rms`. In addition, the `bg_rms` should not be read off the image itself but be predicted from the coadd process, which solves problem 1.

The duplicity is confusion and unnecessary in my mind as the weights need to be inverse variance, modulo some bad pixels that are set to zero.

**Comment by fred3m** [comment]
I understand your concerns, and I agree that the nomenclature is confusing. If we expect users to always use the inverse variance as weights then we should rename `weights` to `variance` and set `weights = 1/variance`. But even in that case we still cannot calculate the RMS without the mean value (of the entire image). Calculating the mean of just the footprint results in the issue that I described above, which is seen in the HSC pipeline version of scarlet since `rms = sqrt(mean**2 + variance)`. So this only works if we assume that the mean value of the image is zero, which may or may not be reasonable.

I'm more concerned now about a difference in API from the pADAM and PGM implementations of scarlet. Recall that we cannot use weights with the PGM implementation because they break our calculation of the Lipschtiz constant, so the weights can only act as a binary mask. Until we fix the PGM implementation so that it correctly uses weights we cannot simplify remove `bg_rms` as an argument or it will completely break the HSC/LSST pipeline. At the very least this ticket has to be blocked by either removing the PGM implementation completely or finding a way to calculate Lipschitz constants with non-binary weights.

**Comment by pmelchior** [comment]
A few things:
* `weights` need to stay even if the term is less definite than `variance` because masked pixels have `weight=0` but undefined variance.
* `bg_rms` is only set for trimming the initial morphology at the noise level, which means that only the background variance is relevant. this quantity can and should be predicted by upstream parts of the pipeline. The mean signal plays no role in it as we're not concerned about Poissonian statistics of bright (parts of) sources.
* PGM is gone in the `adam` now.

Therefore I will now make the change as discussed above.
