### ISSUE TITLE
Deblend failure when weights=0 for one or more images?

### ISSUE THREAD

**Issue by entaylor** [pmelchior/scarlet#245]
I'm running into an issue when trying to deblend a set of images, where the data are incomplete in one or more images.

What i have done is to set the values of both images and weights to be zero where no good data exist.  
![missing_data_example](https://user-images.githubusercontent.com/12062965/123023815-6b0aaf80-d41b-11eb-8b3f-6d8f68702d46.png)

I am uploading an image to illustrate a problem case.  From left to right, the columns show: the imaging data; the weights associated with the imaging; the rendered models after deblending, obtained as observation.render(blend.get_model()).

Two things happen.  First, the fluxes associated with those images where data are missing blow up to very large numbers.  This is sort of understandable, in that the fluxes are unconstrained on the interval of positive numbers.  The second is the bigger problem: the fluxes associated with images that do have data are driven to zero: ~1e-20.  This shouldn't happen, because the fluxes here **can** be well constrained.

It seems superficially that the masking of bad/missing data via setting weights to zero isn't fully respected in the case where some large fraction of one or more images is bad/missing, with the bad behaviour somehow tied to an overall normalisation of the spectrum.  

I've also attached the same case, but excluding the first two images (where data are missing), to show the 'good' solution.  I could include in my pipeline a check for missing data (though i'm not sure what the right condition might be precisely: the centre pixel? Some fraction of the bounding box?), but i feel like the code should be able to cope with this case?
![missing_data_example_noproblem](https://user-images.githubusercontent.com/12062965/123025840-9c38af00-d41e-11eb-9a53-d44915a2fe72.png)

**Comment by fred3m** [comment]
Thanks for passing this along, this isn't something that we've come across before, and we do run this on images with zero weighted regions. But I did a test run just now using three different configurations: the first configuration was the full image with the default weights, the second configuration had zero weights and zero image values for the bluest band from [:60, 40:] (the lower right corner), and the last configuration used zero weights and image values in the reddest band from [:60, 40:].

Original
<img width="929" alt="Screen Shot 2021-06-23 at 12 13 11 PM" src="https://user-images.githubusercontent.com/2251900/123132754-123c1680-d41d-11eb-8333-b4b73396aac0.png">

Blue zeros
<img width="931" alt="Screen Shot 2021-06-23 at 12 16 45 PM" src="https://user-images.githubusercontent.com/2251900/123132818-241db980-d41d-11eb-8491-27e3e3f9dabb.png">

Red zeros
<img width="938" alt="Screen Shot 2021-06-23 at 12 16 07 PM" src="https://user-images.githubusercontent.com/2251900/123132796-1e27d880-d41d-11eb-96b1-cc10aa7d952f.png">


scarlet seems to be able to deblend bright objects with significant flux in all bands even with missing data (see source 0), and even faint sources if the majority of their flux is in one of the bands with data at the location of the peak. The struggle seams to occur when a faint sources has most of its flux in a band that is missing data, and it looks like this has to do with initialization.

To test this idea I initialized all of my models using the image and weights with no data in the reddest band. Then I set the SED for all of the faint sources in that band to zero:

```
for source in sources:
        if isinstance(source, scarlet.MultiExtendedSource):
            pass
        else:
            sed = source.parameters[0]
            sed[bad_band] = 0
```

Then I ran `blend.fit` as normal and obtained the following, which looks roughly correct:
<img width="935" alt="Screen Shot 2021-06-23 at 12 29 31 PM" src="https://user-images.githubusercontent.com/2251900/123135157-77910700-d41f-11eb-8c71-28215fddb420.png">

So it looks like the issue is that when a faint source is initialized with the majority of its flux in a band with missing data, there can be non-zero initial flux in the missing band that can never be removed. So the optimizer makes a futile attempt to suppress the flux by using an ever increasing negative gradient update, which suppresses flux in all bands to the minimum allowable value `1e-20` (used to prevent divergence in the gradient update).

This is something that our initial models should correct for, and we should definitely schedule an update to do so. In the meantime I would recommend implementing the above, which seems stable (but I would add a flag to note that there is missing data in a band or bands).

**Comment by entaylor** [comment]
# dirtyspacenews ! : )

Thanks for this.  I'll add the workaround/check for now, and stay tuned for updates.

**Comment by pmelchior** [comment]
This appears to be an issue with the `set_spectrum` method that solves for the best spectrum amplitude given the initial morphology: https://github.com/pmelchior/scarlet/blob/92b247d415d2e958b7683ff61b5b2f7328b8e389/scarlet/initialization.py#L569-L574

This solver will go haywire if the weights are zero everywhere the morphology is non-zero. We need to catch that.
